### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by chi6rag** [bigbinary/how-credit-card-processing-works#2]
https://github.com/bigbinary/how-credit-card-processing-works/tree/master/ebook/ch7

![screen shot 2015-07-02 at 1 43 18 pm](https://cloud.githubusercontent.com/assets/6065869/8472693/1cac78fa-20c1-11e5-8dd3-310bfb97770c.png)

Incorrect: again
Correct: against

**Comment by prathamesh-sonpatki** [comment]
Thanks @chi6rag :smile:
